### ISSUE TITLE
Working on one file when reading and writing to it

### ISSUE THREAD

**Issue by mgoral** [mgoral/subconvert#1]
``` python
./subconvert.py ~/Wideo/Donnie.Darko.LIMITED.DVDRip.DivX.ViTE.srt -e cp1250 -vf
Overwriting /home/virgo/Wideo/Donnie.Darko.LIMITED.DVDRip.DivX.ViTE.srt
Traceback (most recent call last):
  File "./subconvert.py", line 383, in <module>
    main()
  File "./subconvert.py", line 363, in main
    p['sub']['time_from'].to_time(options.fps)
AttributeError: 'str' object has no attribute 'to_time'


./subconvert.py ~/Wideo/Donnie.Darko.LIMITED.DVDRip.DivX.ViTE.sub -e cp1250 -vf -m microdvd
Overwriting /home/virgo/Wideo/Donnie.Darko.LIMITED.DVDRip.DivX.ViTE.sub
Traceback (most recent call last):
  File "./subconvert.py", line 383, in <module>
    main()
  File "./subconvert.py", line 375, in main
    s = conv.convert(p)
  File "./subconvert.py", line 165, in convert
    gsp_from = self.get_time(sub['sub']['time_from'], 'time_from'),\
  File "./subconvert.py", line 241, in get_time
    return ft.frame
AttributeError: 'str' object has no attribute 'frame'
```

**Comment by mgoral** [comment]
Holy cow... After 4 years that Donnie Darko srt is still my primary experimental file!
